networks:
  todo-network:
    external: true

services:
  web:
    build: .
    container_name: todo-web
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - todo-network
